<div id="container">
        <a class="button" href="index.php?page=exercice1" >Exercice 1</a>
        <a class="button" href="index.php?page=exercice2" >Exercice 2</a>
        <a class="button" href="index.php?page=exercice3" >Exercice 3</a>
        <a class="button" href="index.php?page=exercice4" >Exercice 4</a>
        <a class="button" href="index.php?page=exercice5" >Exercice 5</a>
        <a class="button" href="index.php?page=exercice6" >Exercice 6</a>
        <a class="button" href="index.php?page=exercice7" >Exercice 7</a>
        <a class="button" href="index.php?page=exercice8" >Exercice 8</a>
        <a class="button" href="index.php?page=exercice9" >Exercice 9</a>
        <a class="button" href="index.php?page=exercice10" >Exercice 10</a>
        <a class="button" href="index.php?page=exercice11" >Exercice 11</a>
        <a class="button" href="index.php?page=exercice12" >Exercice 12</a>
        <a class="button" href="index.php?page=exercice13" >Exercice 13</a>
        <a class="button" href="index.php?page=exercice14" >Exercice 14</a>
        <a class="button" href="index.php?page=exercice15" >Exercice 15</a>
        <a class="button" href="index.php?page=exercice16" >Exercice 16</a>
        <a class="button" href="index.php?page=exercice17" >Exercice 17</a>
        <a class="button" href="index.php?page=exercice18" >Exercice 18</a>
        <a class="button" href="index.php?page=exercice19" >Exercice 19</a>
        <a class="button" href="index.php?page=exercice20" >Exercice 20</a>
        <a class="button" href="index.php?page=exercice21" >Exercice 21</a>
        <a class="button" href="index.php?page=exercice22" >Exercice 22</a>
        <a class="button" href="index.php?page=exercice23" >Exercice 23</a>
        <a class="button" href="index.php?page=exercice24" >Exercice 24</a>
        <a class="button" href="index.php?page=exercice25" >Exercice 25</a>
        <a class="button" href="index.php?page=exercice26" >Exercice 26</a>
        <a class="button" href="index.php?page=exercice27" >Exercice 27</a>
        <a class="button" href="index.php?page=exercice28" >Exercice 28</a>
        <a class="button" href="index.php?page=exercice29" >Exercice 29</a>
        <a class="button" href="index.php?page=exercice30" >Exercice 30</a>
</div>
